version: '2'
services:
  easy_ssb_pub:
    build: .
    environment:
      HOST: "${HOST}"
      HOME: "${HOME}"
      DEBUG: "${DEBUG}"
    ports:
      - "80:80"
      - "8008:8008"
      - "8007:8007"
    volumes:
      - $HOME/.ssb:/root/.ssb
      - /srv/easy-ssb-pub:/usr/src/app
    container_name: ssb
    mem_limit: 2048M
    restart: unless-stopped
